### ISSUE TITLE
Facing "Internal Server Error" on deployment of the Model

### ISSUE THREAD

**Issue by aryanjha22** [3ZadeSSG/Minor-Project-Sentiment-Analysis#2]
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." This is the whole message displayed.

Tried deploying your Model using Heroku the index page is fine but when some data is input for prediction this message displays. Please resolve.

**Comment by 3ZadeSSG** [comment]
Hi just wanted to confirm, when you run it locally on your machine, it is working fine?
I will look into the configs this week, maybe there are some changes in Heroku's VMs, will update the code soon.

**Comment by aryanjha22** [comment]
Yaa works fine locally after training the model again on google collab. But not after cloning the app.

**Comment by 3ZadeSSG** [comment]
Hi @aryanjha22 , I made few minor changes after testing the app locally on my setup and also google colab, it is now successfully getting deployed on heroku without any internal server error. The issue was created due to the old verison of libraries used. I had to make 4 changes:-
_1. Fixed **app.py** by adding `import os`
2. In **commons.py** the new version of numpy requires to have `"allow_pickle=True"` in loading the vocab
3. added pytorch version 1.5.1 in requirements (1.6.0 was making the total size exceed 500 MB after deployment, and old version now has issues)
4. Added python 3.7.12 in runtime after looking at the updated list of Heroku's supported versions_

**What you need to do now:-**
_1. Clone the repo (or update your locally saved files with master branch)
2. Train the model again on Google Colab using the notebook and save the vocab file (run last cell) and model checkpoint (model2 checkpoint as per in cell)
3. Downloaded those two files and replace it with current outdated ones
4. Deploy the model using the instructions as mentioned in readme_

If you face any troubles just try to run `heroku logs --tail` in terminal to see logs.




If you face any problems then open this issue again with posting logs in comments
